# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ryan French
description: Ryan French is an Interactive Designer & Front-End Developer from New Zealand. He crafts digital experiences that are both functional and beautiful, where form always follows function.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ryanfrench.me" # the base hostname & protocol for your site

permalink: pretty

paginate: 5
paginate_path: "/journal/page-:num/"

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
  - CNAME
  - node_modules

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
